spring.application.name=product
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/shoping?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA and Hibernate settings
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

# Connection to your local Kafka broker
spring.kafka.bootstrap-servers=localhost:9092

# Consumer group identifier (required for listeners to work)
#spring.kafka.consumer.group-id=demo-group

# Standard serializers and deserializers for simple text messages
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Ensures your consumer reads existing messages if it starts up late
spring.kafka.consumer.auto-offset-reset=earliest